baseURL = "https://text.superbrothers.dev/"
languageCode = "ja-jp"
title = "text.superbrothers.dev"
theme = "paper"
pygmentsCodefences = true
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true
# The length of text in words to show in a `.Summary`.
SummaryLength = 200
