baseURL = "https://text.superbrothers.dev"
languageCode = "ja-jp"
title = "text․superbrothers․dev"
pygmentsCodefences = true
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true
# The length of text in words to show in a `.Summary`.
SummaryLength = 200

googleAnalytics = "UA-10011477-9"

[params]
  images = ["images/avatar_400x400.png"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
